// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVBmOAqd6Tr6r3YVKsx0J2cbc7w6HWoqM',
    appId: '1:576295940263:web:8616035279fd7bcc976b82',
    messagingSenderId: '576295940263',
    projectId: 'chat-me-app-ff833',
    authDomain: 'chat-me-app-ff833.firebaseapp.com',
    storageBucket: 'chat-me-app-ff833.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFQYaZ1lv7w9oPzHPPo-f4pezNMGXXrIo',
    appId: '1:576295940263:android:c998f640bc182027976b82',
    messagingSenderId: '576295940263',
    projectId: 'chat-me-app-ff833',
    storageBucket: 'chat-me-app-ff833.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAS28I1vNeyl7_g0XQhq6LMQtdW6-6n6L8',
    appId: '1:576295940263:ios:58ba5fa84556c341976b82',
    messagingSenderId: '576295940263',
    projectId: 'chat-me-app-ff833',
    storageBucket: 'chat-me-app-ff833.appspot.com',
    iosClientId: '576295940263-4suiqfvep537cts0csgot4i09u139m9g.apps.googleusercontent.com',
    iosBundleId: 'com.example.socketChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAS28I1vNeyl7_g0XQhq6LMQtdW6-6n6L8',
    appId: '1:576295940263:ios:58ba5fa84556c341976b82',
    messagingSenderId: '576295940263',
    projectId: 'chat-me-app-ff833',
    storageBucket: 'chat-me-app-ff833.appspot.com',
    iosClientId: '576295940263-4suiqfvep537cts0csgot4i09u139m9g.apps.googleusercontent.com',
    iosBundleId: 'com.example.socketChatApp',
  );
}
